Concate()

In [1]:
import pandas as pd

india_weather = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [2]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [3]:
df = pd.concat([india_weather,us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [4]:
df = pd.concat([india_weather,us_weather],ignore_index = True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [5]:
df = pd.concat([india_weather,us_weather],keys = ["india","us"])
df

             city  temperature  humidity
india 0    mumbai           32        80
      1     delhi           45        60
      2  banglore           30        78
us    0  new york           21        68
      1   chicago           14        65
      2   orlando           35        75

In [7]:
df.loc["india"]

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [8]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [9]:
temperature_df = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [17]:
windspeed_df = pd.DataFrame ({
    "city":["mumbai","delhi","benglore"],
    "windspeed":[7,12,9]})
windspeed_df

       city  windspeed
0    mumbai          7
1     delhi         12
2  benglore          9

In [18]:
df = pd.concat([temperature_df,windspeed_df],axis = 1)
df

       city  temperature      city  windspeed
0    mumbai           32    mumbai          7
1     delhi           45     delhi         12
2  banglore           30  benglore          9

In [19]:
windspeed_df = pd.DataFrame({
    "city": ["delhi","mumbai"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

     city  windspeed
1   delhi          7
0  mumbai         12

In [20]:
df = pd.concat([temperature_df,windspeed_df],axis = 1)
df

       city  temperature    city  windspeed
0    mumbai           32  mumbai       12.0
1     delhi           45   delhi        7.0
2  banglore           30     NaN        NaN

In [21]:
temperature_df = pd.DataFrame({
    "city": ["mumbai","delhi","banglore"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [22]:
windspeed_df = pd.DataFrame({
    "city": ["delhi","mumbai"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

     city  windspeed
1   delhi          7
0  mumbai         12

In [23]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

       city  temperature    city  windspeed
0    mumbai           32  mumbai       12.0
1     delhi           45   delhi        7.0
2  banglore           30     NaN        NaN

In [24]:
temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           30

In [25]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [26]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0    mumbai           32  Humid
1     delhi           45    Dry
2  banglore           30   Rain