In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Rc\Downloads\Pandas\weather_data.csv')

In [3]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
df.shape

(6, 4)

In [11]:
df.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [13]:
df.tail(2)

        day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [17]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [18]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [19]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [20]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [21]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [24]:
df['event'] # same as df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [25]:
type(df['event'])

pandas.core.series.Series

In [26]:
df[['event','day','temperature']]

   event       day  temperature
0   Rain  1/1/2017           32
1  Sunny  1/2/2017           35
2   Snow  1/3/2017           28
3   Snow  1/4/2017           24
4   Rain  1/5/2017           32
5  Sunny  1/6/2017           31

In [29]:
df['temperature'].max()

35

In [30]:
df['temperature'].min()

24

In [31]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [32]:
df['temperature'].std()

3.8297084310253524

In [33]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [35]:
df[df.temperature >= 32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [36]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [41]:
df[['day','temperature']][df.temperature == df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [43]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [44]:
df.set_index('day',inplace = True)

In [45]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [46]:
df.loc['1/3/2017']

temperature      28
windspeed         2
event          Snow
Name: 1/3/2017, dtype: object

In [47]:
df.reset_index(inplace = True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [48]:
df.set_index('event',inplace = True)

In [49]:
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [51]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7