# Handle Missing Data: Replace Function

In [24]:
import pandas as pd 
import numpy as np 
df = pd.read_csv('C:\\Users\Rc\\Downloads\\Pandas\\weather_data_replace_function.csv')
df

        day temperature windspeed     event
0  1/1/2017         32F      6mph      Rain
1  1/2/2017      -99999      7mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  No Event
4  1/5/2017         32C    -99999      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No Event

In [12]:
new_df = df.replace(-99999,np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [10]:
new_df = df.replace([-99999,-88888],np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [18]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  No Event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        5.0  No Event

In [21]:
new_df = df.replace({
        -99999: np.nan,
        'No Event': 'Sunny',
    })
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0  Sunny

In [25]:
df

        day temperature windspeed     event
0  1/1/2017         32F      6mph      Rain
1  1/2/2017      -99999      7mph     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  No Event
4  1/5/2017         32C    -99999      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No Event

In [26]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True) 
new_df

        day temperature windspeed     event
0  1/1/2017          32         6      Rain
1  1/2/2017      -99999         7     Sunny
2  1/3/2017          28    -99999      Snow
3  1/4/2017      -99999         7  No Event
4  1/5/2017          32    -99999      Rain
5  1/6/2017          31         2     Sunny
6  1/6/2017          34         5  No Event

In [27]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [28]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

C:\Users\Rc\AppData\Local\Temp\ipykernel_10144\4027045839.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica