Read csv

In [24]:
import pandas as pd

df = pd.read_csv("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.csv")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [26]:
import pandas as pd

df0 = pd.read_csv("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.csv",nrows = 3)
df0

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

Missing Value Replace

In [29]:
import pandas as pd

df1 = pd.read_csv("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.csv",na_values = ["not available","n.a."])
df1

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [32]:
df2 = pd.read_csv("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.csv",  na_values={
        'eps': ['not available'],
        'revenue': [-1],
        'people': ['not available','n.a.']
    })
df2

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

Write CSV

In [39]:
df2.to_csv("C:\\Users\\Rc\\Downloads\\Pandas\\new_stock_2.csv",index = False)

In [44]:
df2.columns

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [45]:
df2.to_csv("C:\\Users\\Rc\\Downloads\\Pandas\\new_stock_3.csv", columns=["tickers","price"], index=False)

Read Excel File

In [48]:
import pandas as pd 
df = pd.read_excel("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.xlsx","Sheet1")

In [49]:
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [51]:
def convert_people_cell(cell):
    if cell=="n.a.":
        return 'Sam Walton'
    return cell

def convert_price_cell(cell):
    if cell=="n.a.":
        return 50
    return cell
    
df = pd.read_excel("C:\\Users\\Rc\\Downloads\\Pandas\\stock_data.xlsx","Sheet1", converters= {
        'people': convert_people_cell,
        'price': convert_price_cell
    })
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65     Sam Walton
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani
4    TATA            5.6       -1     50     ratan tata

Write to Excel

In [52]:
df.to_excel("C:\\Users\\Rc\\Downloads\\Pandas\\new_stock_4.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)

In [53]:
df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [55]:
with pd.ExcelWriter('C:\\Users\\Rc\\Downloads\\Pandas\\stocks_weather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")